# require: rubocop-rspec
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'

# Lint
Lint/AssignmentInCondition:
  Enabled: false

# Metrics
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'test/**/*'
    - 'config/**/*'
    - '**/*.rake'
Metrics/LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 100

# Style
Style/AndOr:
  Enabled: false
Style/Documentation:
  Exclude:
    - 'app/controllers/*'
Style/RescueModifier:
  Enabled: false
