# require: rubocop-rspec
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'

# Lint
Lint/AssignmentInCondition:
  Enabled: false

# Metrics
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'test/**/*'
    - 'config/**/*'
    - '**/*.rake'
Metrics/LineLength:
  Max: 160

# Style
Style/AndOr:
  Enabled: false
