version: '3.2'
services:
  mongo:
    image: mongo:3.4
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
    volumes:
      - .:/srv/status
  cron:
    build: .
    command: bundle exec rake lcars:cron
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
