production:
  clients:
    default:
      database: lcars-production
      hosts:
        - localhost:27017
  options:
    log_level: :debug
    raise_not_found_error: false

<% %w(development build test).each do |env| %>
<%= "#{env}:" %>
  clients:
    default:
      database: lcars-<%= env %>
      hosts:
      - localhost:<%= ENV['MONGO_PORT'] || 27017 %>
  options:
    log_level: :info
    raise_not_found_error: false
<%= end %>

## Non-Prod Environments
nonprod:
  clients:
    default:
      database: lcars-nonprod
      hosts:
        - localhost:27017
  options:
    log_level: :info
    raise_not_found_error: false
